import { useCart } from '../context/CartContext';
import { Link } from 'react-router-dom';

const CartModal = () => {
  const { cart, removeFromCart, total, isCartOpen, closeCart } = useCart();

    if (!isCartOpen) return null;

      return (
          <div className="fixed inset-0 z-[999] overflow-hidden">
                <div 
                        className="absolute inset-0 bg-gray-900/60 backdrop-blur-sm transition-opacity"
                                onClick={closeCart}
                                      ></div>

                                            <div className="fixed inset-y-0 right-0 max-w-md w-full flex">
                                                    <div className="h-full w-full bg-white shadow-2xl flex flex-col animate-slide-in-right">
                                                              
                                                                        <div className="px-6 py-6 border-b border-gray-100 flex items-center justify-between bg-gray-50/50">
                                                                                    <h2 className="text-2xl font-black text-gray-900 tracking-tighter">Mi Bolsa</h2>
                                                                                                <button 
                                                                                                              onClick={closeCart}
                                                                                                                            className="p-2 bg-white rounded-full text-gray-400 hover:text-gray-900 hover:bg-gray-100 transition-all shadow-sm"
                                                                                                                                        >
                                                                                                                                                      <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                                                                                                                                                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M6 18L18 6M6 6l12 12" />
                                                                                                                                                                                    </svg>
                                                                                                                                                                                                </button>
                                                                                                                                                                                                          </div>

                                                                                                                                                                                                                    <div className="flex-1 overflow-y-auto p-6 space-y-6">
                                                                                                                                                                                                                                {cart.length === 0 ? (
                                                                                                                                                                                                                                              <div className="h-full flex flex-col items-center justify-center text-gray-400">
                                                                                                                                                                                                                                                              <svg className="w-20 h-20 mb-6 text-gray-200" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                                                                                                                                                                                                                                                                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="1.5" d="M16 11V7a4 4 0 00-8 0v4M5 9h14l1 12H4L5 9z" />
                                                                                                                                                                                                                                                                                                </svg>
                                                                                                                                                                                                                                                                                                                <p className="text-xl font-bold text-gray-500">Tu bolsa está vacía</p>
                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                          ) : (
                                                                                                                                                                                                                                                                                                                                                        cart.map((item) => (
                                                                                                                                                                                                                                                                                                                                                                        <div key={item.id} className="flex gap-4 bg-white p-4 rounded-3xl border border-gray-50 shadow-sm hover:shadow-md transition-all">
                                                                                                                                                                                                                                                                                                                                                                                          <div className="w-24 h-24 bg-gray-50 rounded-2xl p-2 flex-shrink-0">
                                                                                                                                                                                                                                                                                                                                                                                                              <img src={item.thumbnail} alt={item.title} className="w-full h-full object-contain" />
                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div className="flex-1 flex flex-col justify-center">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <h3 className="font-bold text-gray-900 line-clamp-1">{item.title}</h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <p className="text-xs text-gray-400 font-bold uppercase tracking-widest mt-1 mb-2">Cant: {item.quantity}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="flex justify-between items-center mt-auto">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <span className="font-black text-lg text-blue-600">${item.price}</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <button 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  onClick={() => removeFromCart(item.id)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          className="text-red-400 hover:text-red-600 bg-red-50 p-2 rounded-xl transition-colors"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </svg>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {cart.length > 0 && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="border-t border-gray-100 p-6 bg-gray-50">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="flex justify-between items-center mb-6">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <span className="text-gray-500 font-bold">Total Estimado</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <span className="text-3xl font-black text-gray-900">${total.toFixed(2)}</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <Link 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          to="/cart" 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          onClick={closeCart}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          className="w-full flex items-center justify-center bg-gray-900 text-white py-4 rounded-2xl font-black text-lg hover:bg-blue-600 hover:shadow-lg hover:shadow-blue-600/30 transition-all active:scale-95"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Procesar Pago
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </Link>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          export default CartModal;